version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - postgres
  
  frontend:
    build:
      dockerfile: frontend/Dockerfile

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: volleyball_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
